server:
  servlet:
    context-path: '/manager'
  port: 8080
spring:
  profiles:
    active: dev
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    root: DEBUG
    org.springframework.web: TRACE
    org.springframework.web-security: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    reactor.ipc.netty:
      channel.ContextHandler: debug
      reactor.ipc.netty.http.client.HttpClient: debug

security:
  oauth2:
    resource.filter-order: 3
config:
  table: config

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: renderjaviii@gmail.com
  password: ulsafywykyguvmii

# Other properties
spring.mail.properties.mail.smtp:
  auth: true
  connectiontimeout: 5000
  timeout: 5000
  writetimeout: 5000
# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable: true


---
spring:
  profiles: dev, prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/company_db?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=${PROJECT_TIME_ZONE:#{'GMT'}}
    username: root
    password: Password123
    platform: mysql
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
config:
  timezone: 'GMT'