server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  port: ${SERVER_PORT}
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD:password}
    keyStoreType: PKCS12
    keyAlias: ${KEYSTORE_ALIAS}
    enabled: true

trust:
  store: classpath:keystore/keystore.p12
  store.password: ${KEYSTORE_PASSWORD:password}

spring:
  profiles:
    active: ${SERVER_ACTIVE_PROFILE}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cache:
    type: ${SERVER_CACHE_TYPE:'none'}
    redis:
      time-to-live: ${SERVER_CACHE_TTL_MS:1800000}
  redis:
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: 5000ms
      shutdown-timeout: 20000ms
    timeout: 10000ms

security:
  oauth2:
    resource.filter-order: 3
    require-ssl: true
config:
  table: ${SERVER_CONFIG_TABLE_NAME}

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${SPRING_MAIL}
  password: ${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp:
  auth: true
  connectiontimeout: 5000
  timeout: 5000
  writetimeout: 5000
spring.mail.properties.mail.smtp.starttls.enable: true


---
spring:
  profiles: dev, prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${PROJECT_DATABASE_PORT}/${PROJECT_DATABASE_NAME}?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=${SERVER_TIME_ZONE}
    username: ${PROJECT_DATABASE_USER}
    password: ${PROJECT_DATABASE_PASSWORD}
    platform: mysql
    initialization-mode: never
    hikari:
      maximum-pool-size: ${PROJECT_MAX_DB_POOL_SIZE}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: ${PROJECT_DATABASE_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${SERVER_REDIS_HOST}
    port: ${SERVER_REDIS_PORT}
    password:
    ssl: ${SERVER_REDIS_SSL}

config:
  timezone: ${SERVER_TIME_ZONE}


---
spring:
  profiles: dev
  logging:
    level:
      root: DEBUG
      org.springframework.web: TRACE
      org.springframework.web-security: TRACE
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      reactor.ipc.netty:
        channel.ContextHandler: debug
        reactor.ipc.netty.http.client.HttpClient: debug