server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  port: ${SERVER_PORT}
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: renderjaviii
    enabled: true

trust:
  store: classpath:keystore/keystore.p12
  store.password: password

spring:
  profiles:
    active: ${SERVER_ACTIVE_PROFILE}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

security:
  oauth2:
    resource.filter-order: 3
    require-ssl: true
config:
  table: ${SERVER_CONFIG_TABLE_NAME}

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${SPRING_MAIL}
  password: ${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp:
  auth: true
  connectiontimeout: 5000
  timeout: 5000
  writetimeout: 5000
spring.mail.properties.mail.smtp.starttls.enable: true


---
spring:
  profiles: dev, prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${PROJECT_DATABASE_PORT}/${PROJECT_DATABASE_NAME}?zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=${SERVER_TIME_ZONE}
    username: ${PROJECT_DATABASE_USER}
    password: ${PROJECT_DATABASE_PASSWORD}
    platform: mysql
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
config:
  timezone: ${SERVER_TIME_ZONE}
