version: "3.7"
services:
  redis:
    container_name: company-redis
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"

networks:
  default:
    name: "company-cache-network"
